coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
    patch:
      default:
        target: 95%

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
